before_install:
  - pod repo update --silent
  - gem install cocoapods
  - pod install --project-directory=Example
  - instruments -s devices
  - xcodebuild -showsdks
language: objective-c
osx_image: xcode8.1
script:
  - set -o pipefail && xcodebuild -workspace TartuWeather.xcworkspace -scheme TartuWeather -configuration "Debug" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean  build | xcpretty
  - set -o pipefail && xcodebuild -workspace TartuWeather.xcworkspace -scheme meteoTartuWidget -configuration "Debug" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean  build | xcpretty
