before_install:
  - brew update --no-document
  - brew outdated xctool || brew upgrade xctool
language: objective-c
osx_image: xcode7.2
script:
  - xctool clean build -workspace "TartuWeather.xcworkspace" -scheme "TartuWeather" -configuration "Debug" CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO
  - xctool clean build -workspace "TartuWeather.xcworkspace" -scheme "meteoTartuWidget" -configuration "Debug" CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO
