before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
language: objective-c
osx_image: xcode7.2
script:
  - xctool clean build -workspace "TartuWeather.xcworkspace" -scheme "TartuWeather" -configuration "Debug" CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO
    - xctool clean build -workspace "TartuWeather.xcworkspace" -scheme "TodayTartuWeather" -configuration "Debug" CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO
